services:
  - type: web
    name: solun-backend-api
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: ML_SERVICE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false

  - type: web
    name: solun-ml-service
    runtime: python
    rootDir: Backend/ml_service
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_DEBUG
        value: false
